== 만족도조사 등록 API
operation::servey-controller-test/servey-create-test[snippets="request-fields,http-request,http-response"]
== 암호화데이터 복호화 API
operation::servey-controller-test/decrypt-test[snippets="query-parameters,response-fields,http-request,http-response"]
== 만족도 조사 검색 API
operation::servey-controller-test/servey-search-find-test[snippets="query-parameters,http-request,http-response"]
== 엑셀 다운로드 API
operation::servey-controller-test/excel-download-test[snippets="query-parameters,http-request,http-response"]
== 주간 통계 데이터 API
operation::servey-controller-test/weekly-statics-test[snippets="http-request,http-response"]
== 월간 통계 데이터 API
operation::servey-controller-test/monthly-statics-test[snippets="http-request,http-response"]
== 점수 통계 데이터 API
operation::servey-controller-test/score-statics-test[snippets="http-request,http-response"]
== 상담사 통계 데이터 API
operation::servey-controller-test/consultant-statics-test[snippets="http-request,http-response"]
== 전일 통계 데이터 API
operation::servey-controller-test/daily-statics-test[snippets="http-request,http-response"]