CREATE TABLE `mostx_asset_regist` (
  `sno` int NOT NULL AUTO_INCREMENT COMMENT 'sno',
  `wrms_asset_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'WRMS 자산코드',
  `wrms_item_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'WRMS 품목코드',
  `serial_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '시리얼번호',
  `ilsang_product_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '일상구독 상품번호',
  `product_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '상품명',
  `supply_price` int NOT NULL COMMENT '매입원가-공급가',
  `vat` int NOT NULL COMMENT '매입원가-부가세',
  `total_price` int NOT NULL COMMENT '매입원가-합계액',
  `useful_life` tinyint DEFAULT NULL COMMENT '내용연수',
  `warehouse_number` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '창고번호',
  `asset_status` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '자산상태',
  `asset_usage` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '자산용도',
  `regist_department` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '등록자 정보-부서명',
  `regist_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '등록자 정보-성명',
  `asset_regist_date` date NOT NULL DEFAULT (now()) COMMENT '자산등록일자',
  `initial_start_date` date DEFAULT NULL COMMENT '최초 개시일',
  `sales_recognition_amount` int DEFAULT NULL COMMENT '매출인식액',
  `sale_date` date DEFAULT NULL COMMENT '매각(인수)일자',
  `sale_amount` int DEFAULT NULL COMMENT '매각(인수)금액',
  `disposal_date` date DEFAULT NULL COMMENT '폐기일자',
  `disposal_amount` int DEFAULT NULL COMMENT '폐기금액',
  `depreciation_current` int DEFAULT NULL COMMENT '감가상각비(당월)',
  `depreciation_totalprice` int DEFAULT NULL COMMENT '감가상각 누계액',
  `book_value` int DEFAULT NULL COMMENT '장부가액',
  PRIMARY KEY (`sno`),
  UNIQUE KEY `wrms_asset_code` (`wrms_asset_code`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;